#!/usr/bin/env ruby
 
[
'/Users/shabankarumba/Downloads/royalty-free-avatar-clipart-illustration-1166289.jpg','/Users/shabankarumba/Downloads/royalty-free-avatar-clipart-illustration-1166291.jpg', '/Users/shabankarumba/Downloads/ff1a14d1c79bdeb51896cc654fe5327f--create-your-own-avatar-avatar-maker.jpg',
'/Users/shabankarumba/Downloads/4641831.png',
'/Users/shabankarumba/Downloads/Benjohnsone54fbec7a167c5.png',
'/Users/shabankarumba/Downloads/147140.png',
'/Users/shabankarumba/Downloads/FullSizeRender5-1.jpg',
'/Users/shabankarumba/Downloads/business-caricature-drawing-colored-pencils-style-funny-example.jpg',
'/Users/shabankarumba/Downloads/danavatar.png' 
].each do |file|
  avatar = File.open(file)
 user = User.create(username: Faker::Internet.username, email: Faker::Internet.safe_email, sex: Faker::Gender.binary_type, type: 'Trainer', password: 'FakeItTillIMakeit123!')
 
 user.avatar.attach(io: avatar, filename: File.basename(file))
 user.save

 questions = Question.where(user_type: 'Trainer')
   questions.each do |question|
     if !question.options.empty?
       Answer.create(user: user, question: question, answer: question.options.first).save!
     else
       Answer.create(user: user, question: question, answer: Faker::Lorem.paragraph).save!
     end
    end

  Profile.create(short_description: Faker::Lorem.characters(number: 120), long_description: Faker::Lorem.characters(number: 240), qualifications: ['Some course'], user: user).save!
end