development:
  adapter: postgresql
  encoding: unicode
  database: fidness_development
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: fidness_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: fidness_production
  pool: 5
  username: postgres
  password: